# Generated by Django 4.1.7 on 2024-09-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_genre_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
