# Generated by Django 4.2.16 on 2024-09-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_customuser_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("fan", "Fan"), ("professional", "Professional")],
                default="fan",
                max_length=15,
            ),
        ),
    ]
