# Generated by Django 4.2.16 on 2024-09-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_genre_last_updated_alter_genre_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="spotify_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="spotify_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
