# Generated by Django 4.2.16 on 2024-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_customuser_spotify_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="spotify_expires_in",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
